import type { Metadata } from "next";
import "@/fonts/font.css"
import "./globals.css";
import Modals from "@/components/modals";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        {children}
        <Modals />
      </body>
    </html>
  );
}
